language: csharp
dist: trusty
mono: none
dotnet: 2.1.502

solution: Alura.Leilao.sln

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test Alura.Leilao.Tests/Alura.Leilao.Tests.csproj